logo: "/images/JSC_logo.png?raw=true" # your photo (or logo) here
title: J. Scott Cardinal # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <p>
    I'm a professional <a
    href="https://www.linkedin.com/in/cardinal-jscott">archaeologist turned data
    scientist</a>. My work involves:  
  </p>
  
  <ul>
    <li> Unsupervised and semi-supervised machine learning</li>
    <li> GIS and geo-statistics</li>
    <li> A bit of 3D photogrammetry</li>
    <li> Bayesian statistics</li>
    <li> graph-based algorithms</li>
  </ul>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
